.. change::
    :tags: bug, mssql
    :tickets: 5592

    Fixed issue where a SQLAlchemy connection URI for Azure DW with
    ``authentication=ActiveDirectoryIntegrated`` (and no username+password)
    was not constructing the ODBC connection string in a way that was
    acceptable to the Azure DW instance.
